FROM ubuntu:16.04
MAINTAINER Andriy Khavryuchenko <akhavr@khavr.com>

RUN apt-get update -y
RUN apt-get install -y git python-pip wget
RUN pip install --upgrade pip
RUN wget -O /root/makeself.run https://github.com/megastep/makeself/releases/download/release-2.3.0/makeself-2.3.0.run
RUN chmod +x /root/makeself.run
RUN /root/makeself.run --target /root
